[package]
name = "wasm-grate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
swc_common = "0.33.2"
swc_ecma_ast = "0.110.2"
swc_ecma_parser = "0.141.5"

